version: '3'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
      #args:
    
    command: sleep infinity

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

volumes: 
  mongodb-data:

