version: '3'

services: 
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # [Choice] .NET Core version: 3.1, 2.1
        VERSION: 3.1
    
    volumes: 
      - .:/workspace:cached

    command: sleep infinity

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db

volumes: 
  mongodb-data:

